apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamo-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamo-be
  template:
    metadata:
      labels:
        app: dynamo-be
    spec:
      containers:
        - name: dynamo-be
          image: casan3/dynamo-be:latest
          ports:
            - containerPort: 3000
#          env:
#            - name: MONGO_URL
#              value: mongodb://mongo:27017/dev
          imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: dynamo-be-srv
spec:
  selector:
    app: dynamo-be
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer